ktor:
    application:
        modules:
            - com.kotlinbr.ApplicationKt.module
    deployment:
        port: 8080
postgres:
  url: "jdbc:postgresql://localhost/default"
  user: username
  password: password